version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "554:554"  # Проброс порта RTSP, если он доступен на хосте

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking_bot
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
