version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    networks:
      - parking_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking_bot
    ports:
      - "5432:5432"
    networks:
      - parking_network
